environments:
  ci:
    api:
      protocol: http
      host: localhost
      port: 8080
      base_path: /api/v3
      health_endpoint: /openapi.json
    test:
      timeout_seconds: 60
      health_check_interval: 5
