name: Performance Tests

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      test_type:
        description: "Test suite to run"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - pet
          - store
          - user
      debug:
        description: "Run in debug mode"
        required: false
        type: boolean
        default: false

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      REPORT_PATH: ""

    steps:
      - name: Checkout Test Repository
        uses: actions/checkout@v4

      - name: Checkout Swagger Petstore
        uses: actions/checkout@v4
        with:
          repository: swagger-api/swagger-petstore
          path: swagger-petstore

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "temurin"
          cache: "maven"

      - name: Build & Start Petstore
        run: |
          cd swagger-petstore
          mvn clean package -DskipTests
          docker build -t swaggerapi/petstore3:unstable .
          docker run --name swaggerapi-petstore3 -d -p 8080:8080 swaggerapi/petstore3:unstable
          timeout 60 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:8080/api/v3/openapi.json)" != "200" ]]; do sleep 5; done' || false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Dependencies
        working-directory: ./api-test-performance
        run: npm ci

      - name: Set Test Configuration
        working-directory: ./api-test-performance
        run: |
          echo "# Pet simulation variables
          PET_RAMP_DURATION=5
          CREATE_PETS=10
          READ_PETS=20

          # Store simulation variables
          ORDER_RAMP_DURATION=5
          CREATE_ORDERS=10
          READ_ORDERS=20
          DELETE_ORDERS=5
          READ_INVENTORY=15

          # User simulation variables
          USER_RAMP_DURATION=5
          CREATE_USERS=10
          READ_USERS=20
          UPDATE_USERS=8
          DELETE_USERS=5
          AUTH_USERS=25" > .env

          # Make environment variables available
          while IFS= read -r line || [[ -n "$line" ]]; do
            if [[ ! "$line" =~ ^#.*$ ]] && [[ ! -z "$line" ]]; then
              echo "$line" >> $GITHUB_ENV
            fi
          done < .env

      - name: Run Performance Tests
        working-directory: ./api-test-performance
        run: |
          source .env
          if [[ "${{ github.event.inputs.test_type }}" == "pet" ]]; then
            npm run pet-simulation
          elif [[ "${{ github.event.inputs.test_type }}" == "store" ]]; then
            npm run store-simulation
          elif [[ "${{ github.event.inputs.test_type }}" == "user" ]]; then
            npm run user-simulation
          else
            npm run all-simulations
          fi

      - name: Verify Report Directory
        id: verify_report
        run: |
          echo "Checking Gatling report directory contents:"
          ls -la api-test-performance/target/gatling/
          LATEST_REPORT=$(ls -t api-test-performance/target/gatling/jssimulation-* | head -n 1)
          echo "Latest report directory: $LATEST_REPORT"
          if [ ! -f "$LATEST_REPORT/index.html" ]; then
            echo "index.html not found in report directory"
            exit 1
          fi
          echo "report_path=$LATEST_REPORT" >> "$GITHUB_OUTPUT"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.verify_report.outputs.report_path }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Report URL
        run: |
          echo "Performance Test Report will be available at:"
          echo "https://alexandervegazo26.github.io/pet-store-api-test/performance/"

      - name: Wait for GitHub Pages
        run: sleep 30

      - name: Cleanup
        if: always()
        run: |
          docker stop swaggerapi-petstore3 || true
          docker rm swaggerapi-petstore3 || true
          docker image rm swaggerapi/petstore3:unstable || true
          docker system prune -f

concurrency:
  group: "petstore-${{ github.ref }}"
  cancel-in-progress: false
