name: Functional Tests

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      test_type:
        description: "Test suite to run"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - pet
          - store
          - user
      debug:
        description: "Run in debug mode"
        required: false
        type: boolean
        default: false

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Test Repository
        uses: actions/checkout@v4

      - name: Checkout Swagger Petstore
        uses: actions/checkout@v4
        with:
          repository: swagger-api/swagger-petstore
          path: swagger-petstore

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "temurin"
          cache: "maven"

      - name: Build & Start Petstore
        run: |
          cd swagger-petstore
          mvn clean package -DskipTests
          docker build -t swaggerapi/petstore3:unstable .
          docker run --name swaggerapi-petstore3 -d -p 8080:8080 swaggerapi/petstore3:unstable
          timeout 60 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:8080/api/v3/openapi.json)" != "200" ]]; do sleep 5; done' || false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Dependencies
        working-directory: ./api-test-automation
        run: |
          npm install
          npx playwright install --with-deps

      - name: Set Node.js Environment for Path Resolution
        run: echo "NODE_OPTIONS=-r tsconfig-paths/register" >> $GITHUB_ENV

      - name: Build
        working-directory: ./api-test-automation
        env:
          NODE_OPTIONS: "-r tsconfig-paths/register"
        run: |
          npm run build
          echo "Checking compiled files:"
          ls -la dist/src/api || true
          ls -la dist/tests || true

      - name: Run API Tests
        working-directory: ./api-test-automation
        run: npm run test

      - name: Verify Report
        working-directory: ./api-test-automation/playwright-report
        run: |
          if [ ! -f "index.html" ]; then
            echo "No index.html found in Playwright report directory"
            exit 1
          fi

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ./api-test-automation/playwright-report/
          retention-days: 30

      - name: Deploy Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./api-test-automation/playwright-report
          destination_dir: functional-report
          force_orphan: true
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"

      - name: Print Report URL
        run: |
          echo "Functional Test Report will be available at:"
          echo "https://alexandervegazo26.github.io/pet-store-api-test/functional-report/index.html"

      - name: Wait for GitHub Pages
        run: sleep 30

      - name: Cleanup
        if: always()
        run: |
          docker stop swaggerapi-petstore3 || true
          docker rm swaggerapi-petstore3 || true
          docker image rm swaggerapi/petstore3:unstable || true
          docker system prune -f

concurrency:
  group: "petstore-${{ github.ref }}"
  cancel-in-progress: false
